name: "Trigger App Re-Render"

on: 
  workflow_dispatch:

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rendering workflow in the control plane repo
        run: |
          echo "Triggering workflow run on: $CP_REPO - $CP_REF"
          export GH_REPO=$CP_REPO
          GITHUB_TOKEN=$CP_REPO_TOKEN gh workflow run "$WORKFLOW" --ref "$CP_REF"
        env:
          CP_REPO_TOKEN: ${{ secrets.CP_REPO_TOKEN }}
          CP_REPO: ${{ secrets.CP_REPO }}
          CP_REF: ${{ secrets.CP_REF}}
          WORKFLOW: 'transform.yaml'
